import {CONFIG} from "../core/config.js";import {state} from "../core/state.js";
const bagUI=document.querySelector("#deathBag"),bagItems=document.querySelector("#bagItems"),bagClose=document.querySelector("#bagClose"),holdUI=document.querySelector("#bagHold"),holdRing=document.querySelector("#bagHoldRing");
const HOLD_SECONDS=3;let nearbyBag=null,holding=false,holdTime=0,inventorySync=()=>{};
export function setInventorySync(fn){inventorySync=fn||(()=>{})}
export function syncStats(){const coins=document.querySelector("#coins"),drops=document.querySelector("#drops");if(coins)coins.textContent=Math.round(state.coins);if(drops)drops.textContent=state.drops;inventorySync()}
export function closeDeathBag(){state.openBag=null;bagUI.hidden=true}
function renderBag(){if(!state.openBag)return;bagItems.innerHTML="";state.openBag.items.forEach((item,i)=>{const row=document.createElement("button");row.className="bag-item";row.innerHTML=`<span>Drop recuperável</span><b>+${Math.round(item.value)}</b>`;row.onclick=()=>{state.coins+=item.value;state.drops+=item.qty;state.openBag.items.splice(i,1);syncStats();if(!state.openBag.items.length){state.deathBags=state.deathBags.filter(b=>b!==state.openBag);closeDeathBag()}else renderBag()};bagItems.appendChild(row)})}
function openDeathBag(b){state.openBag=b;state.input.x=state.input.y=0;document.querySelector("#stick").style.transform="";holding=false;holdTime=0;holdUI.hidden=true;renderBag();bagUI.hidden=false}
function resetHold(){holding=false;holdTime=0;holdRing.style.setProperty("--progress","0deg")}
holdUI.addEventListener("pointerdown",e=>{e.preventDefault();if(!nearbyBag||state.openBag)return;holding=true;holdUI.setPointerCapture?.(e.pointerId)});
for(const type of ["pointerup","pointercancel"])holdUI.addEventListener(type,resetHold);
bagClose.addEventListener("click",closeDeathBag);
export function updateItems(dt){const p=state.player;for(const l of state.loot){l.t-=dt;if(Math.hypot(p.x-l.x,p.y-l.y)<CONFIG.loot.pickupRange){l.got=true;state.coins+=l.value;state.drops++;syncStats()}}state.loot=state.loot.filter(l=>!l.got&&l.t>0);nearbyBag=state.deathBags.find(b=>Math.hypot(p.x-b.x,p.y-b.y)<CONFIG.deathBag.openRange)||null;holdUI.hidden=!nearbyBag||!!state.openBag||state.mapOpen||state.inventoryOpen;if(!nearbyBag||state.openBag||state.mapOpen||state.inventoryOpen){resetHold();return}if(holding){holdTime=Math.min(HOLD_SECONDS,holdTime+dt);holdRing.style.setProperty("--progress",`${holdTime/HOLD_SECONDS*360}deg`);if(holdTime>=HOLD_SECONDS)openDeathBag(nearbyBag)}}
export function handleDeath(){const p=state.player;if(p.hp>0)return;if(state.drops>0||state.coins>0){const items=[];for(let i=0;i<state.drops;i++)items.push({qty:1,value:state.drops?state.coins/state.drops:0});if(!state.drops&&state.coins>0)items.push({qty:0,value:state.coins});state.deathBags.push({x:p.x,y:p.y,items})}state.coins=state.drops=0;syncStats();p.hp=p.maxHp;p.x=CONFIG.world.width/2;p.y=CONFIG.world.height/2}