import {CONFIG} from "../core/config.js";
const CELL=720,SEED=7319;
function hash(x,y,s=SEED){let n=(x*374761393+y*668265263+s*69069)|0;n=(n^(n>>>13))*1274126177;n^=n>>>16;return(n>>>0)/4294967295}
function region(cx,cy){const r=hash(cx,cy),x=cx*CELL+CELL*(.18+hash(cx,cy,41)*.64),y=cy*CELL+CELL*(.18+hash(cx,cy,97)*.64);if(Math.hypot(x-CONFIG.world.width/2,y-CONFIG.world.height/2)<800)return null;if(r<.065)return{kind:"water",x,y,rx:110+hash(cx,cy,7)*120,ry:75+hash(cx,cy,11)*90};if(r<.23)return{kind:"highland",x,y,rx:280+hash(cx,cy,13)*220,ry:220+hash(cx,cy,17)*180,angle:hash(cx,cy,21)*Math.PI};return null}
function ellipseValue(x,y,f){const c=Math.cos(f.angle||0),s=Math.sin(f.angle||0),dx=x-f.x,dy=y-f.y,rx=dx*c+dy*s,ry=-dx*s+dy*c;return Math.sqrt((rx/f.rx)**2+(ry/f.ry)**2)}
export function terrainHeight(x,y){let h=0;const cx=Math.floor(x/CELL),cy=Math.floor(y/CELL);for(let yy=cy-1;yy<=cy+1;yy++)for(let xx=cx-1;xx<=cx+1;xx++){const f=region(xx,yy);if(!f||f.kind!=="highland")continue;const d=ellipseValue(x,y,f);if(d<1)h=Math.max(h,Math.min(1,(1-d)/.72))}return h}
export function isTerrainBlocked(x,y,pad=0){const cx=Math.floor(x/CELL),cy=Math.floor(y/CELL);for(let yy=cy-1;yy<=cy+1;yy++)for(let xx=cx-1;xx<=cx+1;xx++){const f=region(xx,yy);if(!f||f.kind!=="water")continue;const dx=(x-f.x)/(f.rx+pad),dy=(y-f.y)/(f.ry+pad);if(dx*dx+dy*dy<1)return true}return false}
export function canTraverse(x1,y1,x2,y2,pad=0){if(isTerrainBlocked(x2,y2,pad))return false;const a=terrainHeight(x1,y1),b=terrainHeight(x2,y2);return Math.abs(b-a)<.075}
function drawHighland(ctx,f,sx,sy){const steps=5;for(let i=0;i<steps;i++){const k=1-i*.14;ctx.save();ctx.translate(sx(f.x),sy(f.y));ctx.rotate(f.angle);ctx.fillStyle=["#314132","#354737","#3a4d3b","#405340","#465a45"][i];ctx.beginPath();ctx.ellipse(0,0,f.rx*k,f.ry*k,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#81907822";ctx.lineWidth=3;ctx.stroke();ctx.restore()}ctx.save();ctx.translate(sx(f.x),sy(f.y));ctx.rotate(f.angle);ctx.strokeStyle="#a0a88d33";ctx.lineWidth=2;for(let i=1;i<5;i++){const k=1-i*.14;ctx.beginPath();ctx.ellipse(0,0,f.rx*k,f.ry*k,0,0,Math.PI*2);ctx.stroke()}ctx.restore()}
export function drawTerrain(ctx,camera,viewport){const sx=x=>x-camera.x,sy=y=>y-camera.y,startX=Math.floor(camera.x/CELL)-1,endX=Math.ceil((camera.x+viewport.w)/CELL)+1,startY=Math.floor(camera.y/CELL)-1,endY=Math.ceil((camera.y+viewport.h)/CELL)+1;ctx.fillStyle="#18281f";ctx.fillRect(0,0,viewport.w,viewport.h);
 for(let cy=startY;cy<=endY;cy++)for(let cx=startX;cx<=endX;cx++){const x=cx*CELL,y=cy*CELL,t=hash(cx,cy,3);ctx.fillStyle=t<.3?"#1c3023":t<.55?"#203426":t<.76?"#243629":"#1a2c21";ctx.fillRect(sx(x),sy(y),CELL+1,CELL+1);if(hash(cx,cy,19)<.34){ctx.fillStyle="#554b32";ctx.globalAlpha=.22;ctx.beginPath();ctx.ellipse(sx(x+CELL*(.2+hash(cx,cy,23)*.6)),sy(y+CELL*(.2+hash(cx,cy,29)*.6)),110+hash(cx,cy,31)*150,55+hash(cx,cy,37)*90,hash(cx,cy,43)*Math.PI,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}}
 for(let cy=startY;cy<=endY;cy++)for(let cx=startX;cx<=endX;cx++){const f=region(cx,cy);if(!f)continue;if(f.kind==="highland")drawHighland(ctx,f,sx,sy);else{ctx.fillStyle="#244b50";ctx.beginPath();ctx.ellipse(sx(f.x),sy(f.y),f.rx,f.ry,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#54716b";ctx.lineWidth=5;ctx.stroke()}}
 for(let cy=startY;cy<=endY;cy++)for(let cx=startX;cx<=endX;cx++){if(hash(cx,cy,53)<.5){const x=cx*CELL+80+hash(cx,cy,59)*(CELL-160),y=cy*CELL+80+hash(cx,cy,61)*(CELL-160);if(!isTerrainBlocked(x,y,5)){ctx.fillStyle="#294b32";ctx.beginPath();ctx.arc(sx(x),sy(y),8+hash(cx,cy,67)*10,0,Math.PI*2);ctx.fill()}}}}
