import {CONFIG} from "../core/config.js";
const CELL=520,SEED=7319;
function hash(x,y,s=SEED){let n=(x*374761393+y*668265263+s*69069)|0;n=(n^(n>>>13))*1274126177;n^=n>>>16;return(n>>>0)/4294967295}
function feature(cx,cy){const r=hash(cx,cy),j1=hash(cx,cy,41),j2=hash(cx,cy,97),x=cx*CELL+CELL*(.2+j1*.6),y=cy*CELL+CELL*(.2+j2*.6);if(Math.hypot(x-CONFIG.world.width/2,y-CONFIG.world.height/2)<650)return null;if(r<.075)return{kind:"water",x,y,rx:95+hash(cx,cy,7)*105,ry:70+hash(cx,cy,11)*75};if(r<.19)return{kind:"mountain",x,y,r:62+hash(cx,cy,13)*55};return null}
export function isTerrainBlocked(x,y,pad=0){const minX=Math.floor((x-230)/CELL),maxX=Math.floor((x+230)/CELL),minY=Math.floor((y-230)/CELL),maxY=Math.floor((y+230)/CELL);for(let cy=minY;cy<=maxY;cy++)for(let cx=minX;cx<=maxX;cx++){const f=feature(cx,cy);if(!f)continue;if(f.kind==="mountain"&&Math.hypot(x-f.x,y-f.y)<f.r+pad)return true;if(f.kind==="water"){const dx=(x-f.x)/(f.rx+pad),dy=(y-f.y)/(f.ry+pad);if(dx*dx+dy*dy<1)return true}}return false}
export function drawTerrain(ctx,camera,viewport){const sx=x=>x-camera.x,sy=y=>y-camera.y,startX=Math.floor(camera.x/CELL)-1,endX=Math.ceil((camera.x+viewport.w)/CELL)+1,startY=Math.floor(camera.y/CELL)-1,endY=Math.ceil((camera.y+viewport.h)/CELL)+1;
 ctx.fillStyle="#18281f";ctx.fillRect(0,0,viewport.w,viewport.h);
 for(let cy=startY;cy<=endY;cy++)for(let cx=startX;cx<=endX;cx++){const x=cx*CELL,y=cy*CELL,t=hash(cx,cy,3);ctx.fillStyle=t<.28?"#1c3023":t<.52?"#203426":t<.72?"#243629":"#1a2c21";ctx.fillRect(sx(x),sy(y),CELL+1,CELL+1);const dirt=hash(cx,cy,19);if(dirt<.34){ctx.fillStyle="#4a4530";ctx.globalAlpha=.28;ctx.beginPath();ctx.ellipse(sx(x+CELL*(.2+hash(cx,cy,23)*.6)),sy(y+CELL*(.2+hash(cx,cy,29)*.6)),90+hash(cx,cy,31)*120,45+hash(cx,cy,37)*75,hash(cx,cy,43)*Math.PI,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}
 const f=feature(cx,cy);if(!f)continue;if(f.kind==="water"){ctx.fillStyle="#244b50";ctx.beginPath();ctx.ellipse(sx(f.x),sy(f.y),f.rx,f.ry,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#54716b";ctx.lineWidth=5;ctx.stroke()}else{const px=sx(f.x),py=sy(f.y),r=f.r;ctx.fillStyle="#35423a";ctx.beginPath();ctx.moveTo(px-r,py+r*.55);ctx.lineTo(px-r*.42,py-r*.55);ctx.lineTo(px,py-r);ctx.lineTo(px+r*.38,py-r*.42);ctx.lineTo(px+r,py+r*.55);ctx.closePath();ctx.fill();ctx.fillStyle="#667069";ctx.beginPath();ctx.moveTo(px,py-r);ctx.lineTo(px-r*.15,py-r*.38);ctx.lineTo(px+r*.25,py-r*.5);ctx.closePath();ctx.fill()}}
 // deterministic vegetation details
 for(let cy=startY;cy<=endY;cy++)for(let cx=startX;cx<=endX;cx++){if(hash(cx,cy,53)<.45){const x=cx*CELL+70+hash(cx,cy,59)*(CELL-140),y=cy*CELL+70+hash(cx,cy,61)*(CELL-140);ctx.fillStyle="#294b32";ctx.beginPath();ctx.arc(sx(x),sy(y),8+hash(cx,cy,67)*10,0,Math.PI*2);ctx.fill()}}
}