import {CONFIG} from "../core/config.js";
const CELL=12000,SEED=7319;
function hash(x,y,s=SEED){let n=(x*374761393+y*668265263+s*69069)|0;n=(n^(n>>>13))*1274126177;n^=n>>>16;return(n>>>0)/4294967295}
function region(cx,cy){const r=hash(cx,cy),x=cx*CELL+CELL*(.18+hash(cx,cy,41)*.64),y=cy*CELL+CELL*(.18+hash(cx,cy,97)*.64);if(Math.hypot(x-CONFIG.world.width/2,y-CONFIG.world.height/2)<3500)return null;if(r<.10)return{kind:"water",x,y,rx:1800+hash(cx,cy,7)*2600,ry:1200+hash(cx,cy,11)*1900};if(r<.46)return{kind:"highland",x,y,rx:6200+hash(cx,cy,13)*6500,ry:4800+hash(cx,cy,17)*5200,angle:hash(cx,cy,21)*Math.PI};return null}
function ellipseValue(x,y,f){const c=Math.cos(f.angle||0),s=Math.sin(f.angle||0),dx=x-f.x,dy=y-f.y,rx=dx*c+dy*s,ry=-dx*s+dy*c;return Math.sqrt((rx/f.rx)**2+(ry/f.ry)**2)}
export function terrainHeight(x,y){let h=0;const cx=Math.floor(x/CELL),cy=Math.floor(y/CELL);for(let yy=cy-2;yy<=cy+2;yy++)for(let xx=cx-2;xx<=cx+2;xx++){const f=region(xx,yy);if(!f||f.kind!=="highland")continue;const d=ellipseValue(x,y,f);if(d<1)h=Math.max(h,Math.min(1,(1-d)/.72))}return h}
export function isTerrainBlocked(x,y,pad=0){const cx=Math.floor(x/CELL),cy=Math.floor(y/CELL);for(let yy=cy-2;yy<=cy+2;yy++)for(let xx=cx-2;xx<=cx+2;xx++){const f=region(xx,yy);if(!f||f.kind!=="water")continue;const dx=(x-f.x)/(f.rx+pad),dy=(y-f.y)/(f.ry+pad);if(dx*dx+dy*dy<1)return true}return false}
export function canTraverse(x1,y1,x2,y2,pad=0){if(isTerrainBlocked(x2,y2,pad))return false;const a=terrainHeight(x1,y1),b=terrainHeight(x2,y2);return Math.abs(b-a)<.035}
function drawHighland(ctx,f,sx,sy){const steps=5;for(let i=0;i<steps;i++){const k=1-i*.14;ctx.save();ctx.translate(sx(f.x),sy(f.y));ctx.rotate(f.angle);ctx.fillStyle=["#314132","#354737","#3a4d3b","#405340","#465a45"][i];ctx.beginPath();ctx.ellipse(0,0,f.rx*k,f.ry*k,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#81907822";ctx.lineWidth=3;ctx.stroke();ctx.restore()}ctx.save();ctx.translate(sx(f.x),sy(f.y));ctx.rotate(f.angle);ctx.strokeStyle="#a0a88d33";ctx.lineWidth=2;for(let i=1;i<5;i++){const k=1-i*.14;ctx.beginPath();ctx.ellipse(0,0,f.rx*k,f.ry*k,0,0,Math.PI*2);ctx.stroke()}ctx.restore()}
export function drawTerrain(ctx,camera,viewport){const sx=x=>x-camera.x,sy=y=>y-camera.y,startX=Math.floor(camera.x/CELL)-1,endX=Math.ceil((camera.x+viewport.w)/CELL)+1,startY=Math.floor(camera.y/CELL)-1,endY=Math.ceil((camera.y+viewport.h)/CELL)+1;ctx.fillStyle="#18281f";ctx.fillRect(0,0,viewport.w,viewport.h);
 for(let cy=startY;cy<=endY;cy++)for(let cx=startX;cx<=endX;cx++){const x=cx*CELL,y=cy*CELL,t=hash(cx,cy,3);ctx.fillStyle=t<.3?"#1c3023":t<.55?"#203426":t<.76?"#243629":"#1a2c21";ctx.fillRect(sx(x),sy(y),CELL+1,CELL+1);if(hash(cx,cy,19)<.34){ctx.fillStyle="#554b32";ctx.globalAlpha=.22;ctx.beginPath();ctx.ellipse(sx(x+CELL*(.2+hash(cx,cy,23)*.6)),sy(y+CELL*(.2+hash(cx,cy,29)*.6)),110+hash(cx,cy,31)*150,55+hash(cx,cy,37)*90,hash(cx,cy,43)*Math.PI,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}}
 for(let cy=startY;cy<=endY;cy++)for(let cx=startX;cx<=endX;cx++){const f=region(cx,cy);if(!f)continue;if(f.kind==="highland")drawHighland(ctx,f,sx,sy);else{ctx.fillStyle="#244b50";ctx.beginPath();ctx.ellipse(sx(f.x),sy(f.y),f.rx,f.ry,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#54716b";ctx.lineWidth=5;ctx.stroke()}}
 for(let cy=startY;cy<=endY;cy++)for(let cx=startX;cx<=endX;cx++){if(hash(cx,cy,53)<.5){const x=cx*CELL+80+hash(cx,cy,59)*(CELL-160),y=cy*CELL+80+hash(cx,cy,61)*(CELL-160);if(!isTerrainBlocked(x,y,5)){ctx.fillStyle="#294b32";ctx.beginPath();ctx.arc(sx(x),sy(y),8+hash(cx,cy,67)*10,0,Math.PI*2);ctx.fill()}}}}

export function drawWorldMapTerrain(ctx,w,h){const cols=150,rows=Math.max(70,Math.round(cols*(CONFIG.world.height/CONFIG.world.width)*(h/w))),cw=w/cols,ch=h/rows;ctx.fillStyle="#1d3325";ctx.fillRect(0,0,w,h);
 const heightGrid=Array.from({length:rows},()=>new Float32Array(cols));const waterGrid=Array.from({length:rows},()=>new Uint8Array(cols));
 for(let gy=0;gy<rows;gy++)for(let gx=0;gx<cols;gx++){const wx=(gx+.5)/cols*CONFIG.world.width,wy=(gy+.5)/rows*CONFIG.world.height,hgt=terrainHeight(wx,wy),water=isTerrainBlocked(wx,wy,0);heightGrid[gy][gx]=hgt;waterGrid[gy][gx]=water?1:0;ctx.fillStyle=water?"#285a62":hgt>.72?"#68745c":hgt>.48?"#536348":hgt>.22?"#3d503b":hgt>.06?"#304433":"#203727";ctx.fillRect(gx*cw,gy*ch,cw+1,ch+1)}
 // Local contour edges only: never connect unrelated elevation samples.
 ctx.lineWidth=1;for(const level of [.22,.48,.72]){ctx.strokeStyle=level>.7?"#c0c7a555":"#a5b18c3d";ctx.beginPath();for(let gy=0;gy<rows-1;gy++)for(let gx=0;gx<cols-1;gx++){const a=heightGrid[gy][gx],right=heightGrid[gy][gx+1],down=heightGrid[gy+1][gx];if((a-level)*(right-level)<0){const x=(gx+1)*cw,y=(gy+.5)*ch;ctx.moveTo(x,y-ch*.45);ctx.lineTo(x,y+ch*.45)}if((a-level)*(down-level)<0){const x=(gx+.5)*cw,y=(gy+1)*ch;ctx.moveTo(x-cw*.45,y);ctx.lineTo(x+cw*.45,y)}}ctx.stroke()}
 // Smooth water borders so lakes read as coherent regions.
 ctx.strokeStyle="#6b929255";ctx.lineWidth=1.2;ctx.beginPath();for(let gy=0;gy<rows;gy++)for(let gx=0;gx<cols;gx++)if(waterGrid[gy][gx]){const x=gx*cw,y=gy*ch;if(!waterGrid[gy]?.[gx-1]){ctx.moveTo(x,y);ctx.lineTo(x,y+ch)}if(!waterGrid[gy]?.[gx+1]){ctx.moveTo(x+cw,y);ctx.lineTo(x+cw,y+ch)}if(!waterGrid[gy-1]?.[gx]){ctx.moveTo(x,y);ctx.lineTo(x+cw,y)}if(!waterGrid[gy+1]?.[gx]){ctx.moveTo(x,y+ch);ctx.lineTo(x+cw,y+ch)}}ctx.stroke()}
