import {CONFIG} from "./config.js";import {state} from "./state.js";import {isTerrainBlocked} from "../world/terrain.js";
const KEY="rpg-character-save-v2",LEGACY_KEY="rpg-character-save-v1",INTERVAL=1500,CAPACITY=40;let elapsed=0;
function ensureSafePosition(){const p=state.player;if(!isTerrainBlocked(p.x,p.y,p.r+8))return;const step=64;for(let radius=step;radius<=1600;radius+=step){const points=Math.max(12,Math.ceil(Math.PI*2*radius/step));for(let i=0;i<points;i++){const a=i/points*Math.PI*2,x=p.x+Math.cos(a)*radius,y=p.y+Math.sin(a)*radius;if(x>p.r&&x<CONFIG.world.width-p.r&&y>p.r&&y<CONFIG.world.height-p.r&&!isTerrainBlocked(x,y,p.r+8)){p.x=x;p.y=y;return}}}p.x=CONFIG.world.width/2;p.y=CONFIG.world.height/2}
const validItem=item=>item&&typeof item==="object"&&typeof item.id==="string"&&typeof item.type==="string"&&typeof item.slot==="string";
const validBag=b=>b&&Number.isFinite(b.x)&&Number.isFinite(b.y)&&Array.isArray(b.items);
export function loadSave(){try{let raw=localStorage.getItem(KEY),legacy=false;if(!raw){raw=localStorage.getItem(LEGACY_KEY);legacy=!!raw}if(!raw)return false;const s=JSON.parse(raw),p=s.player||{};if(legacy){state.player.x=CONFIG.world.width/2;state.player.y=CONFIG.world.height/2}else{if(Number.isFinite(p.x))state.player.x=Math.max(0,Math.min(CONFIG.world.width,p.x));if(Number.isFinite(p.y))state.player.y=Math.max(0,Math.min(CONFIG.world.height,p.y))}if(Number.isFinite(p.hp))state.player.hp=Math.max(1,Math.min(state.player.maxHp,p.hp));state.coins=Number.isFinite(s.coins)?Math.max(0,s.coins):0;state.inventory=Array.isArray(s.inventory)?s.inventory.filter(validItem).slice(0,CAPACITY):[];const eq=s.equipment||{};for(const slot of ["head","body","legs","feet","mystic"])state.equipment[slot]=validItem(eq[slot])?eq[slot]:null;state.deathBags=Array.isArray(s.deathBags)?s.deathBags.filter(validBag).slice(-10):[];ensureSafePosition();if(legacy)saveNow();return true}catch(e){console.warn("Save inválido ignorado",e);return false}}
export function saveNow(){try{localStorage.setItem(KEY,JSON.stringify({version:2,world:{width:CONFIG.world.width,height:CONFIG.world.height},savedAt:Date.now(),player:{x:state.player.x,y:state.player.y,hp:state.player.hp},coins:state.coins,inventory:state.inventory.slice(0,CAPACITY),equipment:state.equipment,deathBags:state.deathBags.slice(-10)}))}catch(e){console.warn("Não foi possível salvar",e)}}
export function updateSave(dt){elapsed+=dt;if(elapsed>=INTERVAL/1000){elapsed=0;saveNow()}}
export function initSaveSystem(){loadSave();addEventListener("pagehide",saveNow);document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="hidden")saveNow()})}
