import {state} from "../core/state.js";import {MapSystem} from "../navigation/mapSystem.js";
const canvas=document.querySelector("#canvas"),ctx=canvas.getContext("2d");
export function resize(){const v=state.viewport;v.dpr=Math.min(devicePixelRatio||1,2);v.w=innerWidth;v.h=innerHeight;canvas.width=v.w*v.dpr;canvas.height=v.h*v.dpr;ctx.setTransform(v.dpr,0,0,v.dpr,0,0)}
const sx=x=>x-state.camera.x,sy=y=>y-state.camera.y,visible=(x,y,p=80)=>x>state.camera.x-p&&x<state.camera.x+state.viewport.w+p&&y>state.camera.y-p&&y<state.camera.y+state.viewport.h+p;
export function draw(){const {w:W,h:H}=state.viewport;ctx.clearRect(0,0,W,H);ctx.fillStyle="#15231d";ctx.fillRect(0,0,W,H);ctx.strokeStyle="#ffffff0a";ctx.lineWidth=1;const gx=Math.floor(state.camera.x/64)*64,gy=Math.floor(state.camera.y/64)*64;for(let x=gx;x<state.camera.x+W+64;x+=64){ctx.beginPath();ctx.moveTo(sx(x),0);ctx.lineTo(sx(x),H);ctx.stroke()}for(let y=gy;y<state.camera.y+H+64;y+=64){ctx.beginPath();ctx.moveTo(0,sy(y));ctx.lineTo(W,sy(y));ctx.stroke()}
 for(const l of state.loot){if(!visible(l.x,l.y))continue;ctx.fillStyle="#f7ca4d";ctx.beginPath();ctx.arc(sx(l.x),sy(l.y),l.r,0,7);ctx.fill()}
 for(const b of state.deathBags){if(!visible(b.x,b.y))continue;const x=sx(b.x),y=sy(b.y);ctx.fillStyle="#8d5a2b";ctx.beginPath();ctx.roundRect(x-17,y-12,34,28,8);ctx.fill();ctx.strokeStyle="#e6bd72";ctx.lineWidth=3;ctx.stroke();ctx.beginPath();ctx.arc(x,y-11,9,Math.PI,0);ctx.stroke();ctx.fillStyle="#fff";ctx.font="11px sans-serif";ctx.textAlign="center";ctx.fillText("SACOLA",x,y-22);ctx.textAlign="start"}
 for(const m of state.mobs){if(!visible(m.x,m.y))continue;const x=sx(m.x),y=sy(m.y);ctx.fillStyle=m.hit?"#fff":(m.state==="CHASE"||m.state==="ATTACK")?"#7bea68":"#6ad35d";ctx.beginPath();ctx.arc(x,y,m.r,0,7);ctx.fill();ctx.fillStyle="#000";ctx.beginPath();ctx.arc(x-7,y-3,2.5,0,7);ctx.arc(x+7,y-3,2.5,0,7);ctx.fill();ctx.fillStyle="#401b1b";ctx.fillRect(x-22,y-31,44,5);ctx.fillStyle="#e54b4b";ctx.fillRect(x-22,y-31,44*(m.hp/m.maxHp),5)}
 const p=state.player,px=sx(p.x),py=sy(p.y);if(p.attackCd>.22){ctx.strokeStyle="#ffe47a";ctx.lineWidth=7;ctx.beginPath();ctx.arc(px,py,67,-.8,.8);ctx.stroke()}ctx.fillStyle="#59a7ff";ctx.beginPath();ctx.arc(px,py,p.r,0,7);ctx.fill();ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(px+p.dirX*11,py+p.dirY*11,4,0,7);ctx.fill();
 const a=MapSystem.waypointDirection();if(a!==null){ctx.save();ctx.translate(px,py+p.r+20);ctx.rotate(a+Math.PI/2);ctx.fillStyle="#ffd75a";ctx.shadowColor="#ffd75a";ctx.shadowBlur=8;ctx.beginPath();ctx.moveTo(0,-10);ctx.lineTo(7,7);ctx.lineTo(0,4);ctx.lineTo(-7,7);ctx.closePath();ctx.fill();ctx.restore()}}
export function updateHud(){const p=state.player;document.querySelector("#hp").style.width=(p.hp/p.maxHp*100)+"%";document.querySelector("#hpText").textContent=Math.ceil(p.hp)+"/"+p.maxHp}