import {MapSystem} from "./mapSystem.js";import {state} from "../core/state.js";
export function initWorldMap(){const overlay=document.querySelector("#worldMap"),canvas=document.querySelector("#worldMapCanvas"),ctx=canvas.getContext("2d"),close=document.querySelector("#worldMapClose");
 function setOpen(value){state.mapOpen=value;state.input.x=state.input.y=0;document.querySelector("#stick").style.transform="";overlay.hidden=!value;if(value)draw()}
 close.addEventListener("pointerdown",e=>{e.preventDefault();e.stopPropagation();setOpen(false)});overlay.addEventListener("pointerdown",e=>{if(e.target===overlay)setOpen(false)});
 canvas.addEventListener("pointerdown",e=>{e.preventDefault();e.stopPropagation();const r=canvas.getBoundingClientRect();MapSystem.setWaypoint((e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height);draw()});
 function draw(){if(!state.mapOpen)return;const r=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),w=Math.max(1,Math.round(r.width)),h=Math.max(1,Math.round(r.height));if(canvas.width!==w*dpr||canvas.height!==h*dpr){canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}ctx.clearRect(0,0,w,h);ctx.fillStyle="#14251c";ctx.fillRect(0,0,w,h);ctx.strokeStyle="#ffffff12";for(let i=1;i<8;i++){ctx.beginPath();ctx.moveTo(w*i/8,0);ctx.lineTo(w*i/8,h);ctx.stroke();ctx.beginPath();ctx.moveTo(0,h*i/8);ctx.lineTo(w,h*i/8);ctx.stroke()}
 const wp=MapSystem.waypoint();if(wp){const q=MapSystem.worldToNormalized(wp.x,wp.y);ctx.strokeStyle="#ffd75a";ctx.lineWidth=2;ctx.beginPath();ctx.arc(q.x*w,q.y*h,8,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(q.x*w-11,q.y*h);ctx.lineTo(q.x*w+11,q.y*h);ctx.moveTo(q.x*w,q.y*h-11);ctx.lineTo(q.x*w,q.y*h+11);ctx.stroke()}
 const p=MapSystem.playerNormalized();ctx.fillStyle="#72b8ff";ctx.beginPath();ctx.arc(p.x*w,p.y*h,7,0,Math.PI*2);ctx.fill();ctx.strokeStyle="#fff";ctx.lineWidth=2;ctx.stroke()}
 return{open:()=>setOpen(true),close:()=>setOpen(false),draw}}
